server:
  port: 8083
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    kubernetes:
      discovery:
        catalogServicesWatchDelay: 5000
        service-labels:
          type: spring-boot
  boot:
    admin:
      monitor:
        status-interval: 10s
        status-lifetime: 10s
      client:
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
logging:
  file: target/app.log