server:
  port: 8083
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    kubernetes:
      discovery:
        catalogServicesWatchDelay: 5000
        service-labels:
          type: spring-boot
  boot:
    admin:
      monitor:
        status-interval: 3s
        status-lifetime: 3s