# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX = 'peru/ubuntu-18.04-desktop-amd64'
VAGRANT_BOX_VERSION = '20190901.01'
VM_NAME = 'k8s-eshop-ui'

Vagrant.configure('2') do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.box_version = VAGRANT_BOX_VERSION
  config.vm.hostname = VM_NAME
  
  config.vm.network "private_network", ip: "192.168.50.4" 
  
  config.vm.network "forwarded_port", guest: 30100, host: 80
  config.vm.network "forwarded_port", guest: 30123, host: 4001
  config.vm.network "forwarded_port", guest: 31631, host: 4002
  config.vm.network "forwarded_port", guest: 30181, host: 4003
  config.vm.network "forwarded_port", guest: 80, host: 4004
  config.vm.network "forwarded_port", guest: 30101, host: 4005
  config.vm.network "forwarded_port", guest: 30102, host: 4006
  config.vm.network "forwarded_port", guest: 30103, host: 4007
  config.vm.network "forwarded_port", guest: 30104, host: 4008
  config.vm.network "forwarded_port", guest: 30303, host: 4009 # Spring boot admin
  config.vm.network "forwarded_port", guest: 31625, host: 4010 # SonarQube
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # nodejs dev server
  config.vm.network "forwarded_port", guest: 4200, host: 4200 # angular dev server

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'virtualbox' do |v|
    v.name = VM_NAME
    v.memory = 10240 # 10GB
    v.cpus = 4
    v.gui = true

    v.customize ["modifyvm", :id, "--vram", "128"]
  end
  
  config.vm.provision "shell", path: "vagrant-provision-script.sh"
end