apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar-svc
  name: sonar-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      name: sonarport
  selector:
    name: sonarqube
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: e-shop-gateway-ingress-sonar
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: sonar.k8s-eshop.io
      http:
        paths:
          - path: /
            backend:
              serviceName: sonar-svc
              servicePort: 80