apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar-svc
  name: sonar-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      name: sonarport
  selector:
    name: sonarqube