apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-service-dep
  annotations:
    # Jaeger tracing sidecar
    sidecar.jaegertracing.io/inject: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: files-service
  template:
    metadata:
      labels:
        app: files-service
    spec:
      restartPolicy: Always
      containers:
        - name: files-service
          image: giopeto/e-shop-files-service:V23



          ports:
            - containerPort: 8082
          resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 5

          
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: files-service-svc
spec:
  selector:
    app: files-service
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8082
      # Port to forward to inside the pod
      targetPort: 8082
      # Port accessible outside cluster
      nodePort: 30103
  type: LoadBalancer