apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: files-service-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: files-service
    spec:
      restartPolicy: Always
      containers:
        - name: files-service
          image: giopeto/e-shop-files-service:V6
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: files-service-svc
spec:
  selector:
    app: files-service
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8082
      # Port to forward to inside the pod
      targetPort: 8082
      # Port accessible outside cluster
      nodePort: 30103
  type: LoadBalancer