apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-dep
  labels:
    artifactory: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      artifactory: nexus
  template:
    metadata:
      labels:
        artifactory: nexus
    spec:
      securityContext:
        fsGroup: 200
        runAsUser: 200
        runAsGroup: 200
      # securityContext:
      #   runAsUser: 200
      #   runAsGroup: 2000
      #   fsGroup: 2000
      # initContainers:
      #   - name: volume-mount-hack
      #     image: busybox
      #     command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
      #     volumeMounts:
      #     - name: hostvol-nexus
      #       mountPath: /nexus-data
      containers:
        - name: nexus
          #image: sonatype/nexus3:3.19.1
          image: sonatype/nexus3:3.15.2
          #command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          #command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: hostvol-nexus
              mountPath: /nexus-data
      volumes:
        - name: hostvol-nexus
          persistentVolumeClaim:
            claimName: nexus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  labels:
    app: nexus
spec:
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30181
      protocol: TCP
  selector:
    artifactory: nexus
  type: LoadBalancer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-task-pv-volume
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/vagrant/persistent-volumes-k8s/nexus
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  labels:
    app: nexuspv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi