apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-dep
  namespace: k8s-eshop
  labels:
    artifactory: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      artifactory: nexus
  template:
    metadata:
      labels:
        artifactory: nexus
    spec:
      securityContext:
        fsGroup: 200
        runAsUser: 200
        runAsGroup: 200
      containers:
        - name: nexus
          image: sonatype/nexus3:3.15.2
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: hostvol-nexus
              mountPath: /nexus-data
      volumes:
        - name: hostvol-nexus
          persistentVolumeClaim:
            claimName: nexus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: k8s-eshop
  labels:
    app: nexus
spec:
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30181
      protocol: TCP
  selector:
    artifactory: nexus
  type: LoadBalancer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-task-pv-volume
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/vagrant/persistent-volumes-k8s/nexus
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: k8s-eshop
  labels:
    app: nexuspv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi