apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: admin
      containers:
        - image: giopeto/e-shop-admin-server:V1
          imagePullPolicy: Always
          name: admin
          env:
            - name: spring.profiles.active
              value: k8s
          ports:
            - containerPort: 8083
      restartPolicy: Always
  selector:
    matchLabels:
      app: admin