apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: admin
      containers:
        - image: giopeto/e-shop-spring-boot-admin-service:V11 # joshiste/admin:sio-bcn
          imagePullPolicy: Always
          name: admin
          env:
            - name: spring.profiles.active
              value: k8s
            # - name: management.endpoints.web.exposure.include
            #   value: "*"
            # - name: management.endpoint.health.show-details
            #   value: "always"
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: admin




