apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: k8s-eshop
  labels:
    type: spring-boot
spec:
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8083
      # Port to forward to inside the pod
      targetPort: 8083
      # Port accessible outside cluster
      nodePort: 30303
  type: LoadBalancer
  selector:
    app: admin