# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'bento/ubuntu-18.04'
# Box / OS version
# VAGRANT_BOX_VERSION = '20190901.01'
# Memorable name for your
VM_NAME = 'k8s-eshop-bento'

Vagrant.configure('2') do |config|
  config.vm.box = VAGRANT_BOX
  # config.vm.box_version = VAGRANT_BOX_VERSION
  config.vm.hostname = VM_NAME
  
  config.vm.network "private_network", ip: "192.168.50.4" 
  
  config.vm.network "forwarded_port", guest: 30100, host: 80
  config.vm.network "forwarded_port", guest: 30123, host: 4001
  config.vm.network "forwarded_port", guest: 31631, host: 4002
  config.vm.network "forwarded_port", guest: 30181, host: 4003
  config.vm.network "forwarded_port", guest: 80, host: 4004
  config.vm.network "forwarded_port", guest: 30101, host: 4005
  config.vm.network "forwarded_port", guest: 30102, host: 4006
  config.vm.network "forwarded_port", guest: 30103, host: 4007
  config.vm.network "forwarded_port", guest: 30104, host: 4008

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'virtualbox' do |v|
    v.name = VM_NAME
    v.memory = 10240 # 10GB 4096 # 4GB
    v.cpus = 4
    #v.gui = true

  	v.customize ["modifyvm", :id, "--vram", "128"]
  end
  
  config.vm.provision "shell", path: "vagrant-provision-script.sh"
end